# Generated by Django 5.1 on 2024-09-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='image/')),
                ('upload_to', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
