# Generated by Django 5.1 on 2024-09-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectHome',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='image/')),
                ('h', models.CharField(max_length=255)),
                ('p', models.CharField(max_length=999)),
                ('link', models.CharField(max_length=999)),
            ],
        ),
    ]
