# Generated by Django 5.1 on 2024-09-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='cv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='pdf/')),
                ('upload_to', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
