# Generated by Django 5.1 on 2024-09-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phoneNumber',
            field=models.CharField(max_length=10),
        ),
    ]
